# Generated by Django 5.2.6 on 2025-09-23 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]
    # 1번 설계도를 기반으로 2번 설계도를 만듦
    # 만약 1번 설계도가 없다면 2번 설계도를 만들 수 없음
    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            # 장고가 잡아낸 오류 default=django.utils.timezone.now
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
